# Generated by Django 5.2 on 2025-07-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0002_conditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='referenced_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_variables', to='strings_api.string'),
        ),
        migrations.AddField(
            model_name='variable',
            name='variable_type',
            field=models.CharField(choices=[('trait', 'Trait Variable'), ('string', 'String Variable')], default='trait', max_length=10),
        ),
    ]
