# Generated by Django 5.2 on 2025-07-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0003_variable_referenced_string_variable_variable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_conditional',
            field=models.BooleanField(default=False),
        ),
    ]
