# Generated by Django 5.2 on 2025-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0004_variable_is_conditional'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
