# Generated by Django 5.2 on 2025-07-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0005_add_content_to_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='strings_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='strings_api.dimension')),
            ],
            options={
                'unique_together': {('dimension', 'value')},
            },
        ),
        migrations.CreateModel(
            name='StringDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_assignments', to='strings_api.dimensionvalue')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='strings_api.string')),
            ],
            options={
                'unique_together': {('string', 'dimension_value')},
            },
        ),
    ]
