# Generated by Django 5.2 on 2025-07-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0006_add_dimensions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'project')},
        ),
    ]
