# Generated by Django 5.2 on 2025-07-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0007_alter_variable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together={('name', 'project')},
        ),
    ]
