# Generated by Django 5.2 on 2025-07-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0008_alter_dimension_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='content',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='referenced_string',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='variable_type',
        ),
        migrations.AddField(
            model_name='string',
            name='is_variable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='string',
            name='variable_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='string',
            unique_together={('variable_name', 'project')},
        ),
    ]
