# Generated by Django 5.2 on 2025-07-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0009_remove_variable_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableDimensionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_values', to='strings_api.dimensionvalue')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='strings_api.variable')),
            ],
            options={
                'unique_together': {('variable', 'dimension_value')},
            },
        ),
    ]
