# Generated by Django 5.2 on 2025-07-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0010_variabledimensionvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='string',
            name='is_variable',
        ),
        migrations.AddField(
            model_name='string',
            name='variable_hash',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
