# Generated by Django 5.2 on 2025-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0012_auto_20250711_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='is_conditional',
            field=models.BooleanField(default=False),
        ),
    ]
