# Generated by Django 5.2 on 2025-07-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0013_add_conditional_to_strings'),
    ]

    operations = [
        # Remove VariableValue model (depends on Trait)
        migrations.DeleteModel(
            name='VariableValue',
        ),
        
        # Remove Trait model
        migrations.DeleteModel(
            name='Trait',
        ),
    ]
