# Generated by Django 5.2 on 2025-07-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0014_remove_traits'),
    ]

    operations = [
        # Remove the variables field from String model first
        migrations.RemoveField(
            model_name='string',
            name='variables',
        ),
        # Delete the models
        migrations.DeleteModel(
            name='VariableDimensionValue',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
        # Add is_split_variable field to String model
        migrations.AddField(
            model_name='string',
            name='is_split_variable',
            field=models.BooleanField(default=False),
        ),
    ] 