# Generated by Django 5.2 on 2025-07-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0015_remove_variable_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
