# Generated by Django 5.2 on 2025-08-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0016_alter_string_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='string',
            old_name='is_split_variable',
            new_name='is_conditional_container',
        ),
    ]
