# Generated by Django 5.2 on 2025-08-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0017_rename_split_variable_to_conditional_container'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conditional',
        ),
    ]
