# Generated by Django 5.2 on 2025-09-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0018_remove_conditional_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='string',
            options={'ordering': ['-created_at']},
        ),
    ]
