# Generated by Django 5.2 on 2025-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0019_alter_string_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
