# Generated by Django 5.2 on 2025-11-12 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0020_string_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='controlled_by_spawn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controls_spawns', to='strings_api.string'),
        ),
    ]
