# Generated by Django 5.2 on 2026-01-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings_api', '0021_string_controlled_by_spawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
